### ISSUE TITLE
Scope values never get hidden removed if set asynchronously 

### ISSUE THREAD

**Issue by robertsimmons** [Dragnipur/tiny-angular-wordcloud#8]
See: http://plnkr.co/edit/972poSyxinLZAsPRAmhI?p=preview

I used a $timeout for the example, but originally noticed it using $http.

For now I just didn't make the hidden class actually set the visibility to hidden.

**Comment by lopsided** [comment]
I am hitting this issue too, did you find a fix or workaround?

**Comment by lopsided** [comment]
OK so my workaround is to recompile the element when I fetch new data from the backend. I have the tang cloud directive inside my own directive, and so I recompile my directive when the data changes:

```
controller: function ($scope, $element) {
                    var loadData = function () {
                            DataSrv.loadData('words').then(function (words) {
                                $scope.words = words;
                                $compile($element.contents())($scope);
                            });
                    };
                    $rootScope.$on('params:changed', loadData);
                    loadData();
                }
```

Maybe this will help someone

**Comment by robertsimmonsmurata** [comment]
I've switched positions and no longer have access to the code, but I believe the workaround I did was what was mentioned in my original post - I just made the elements never be hidden in the first place. You could just hide the entire word cloud using ng-if and a typical div to stop them from showing until the data was in place.

**Comment by Dragnipur** [comment]
I've added a watch on the scope variable, that fixed it. Thanks for noticing!

**Comment by lopsided** [comment]
I tried that too and that fixed the initial load but when I replaced the collection of words with a new one then while it did replace the words, the positions were continuing to spiral outwards, leaving a circular space in the middle of the new cloud.

**Comment by Dragnipur** [comment]
I can't seem to recreate that scenario. When I load the words and then reload them within a timeout, everything works fine. Can you create a plnkr?

**Comment by lopsided** [comment]
Sorry I made that comment before checking out your changes. I had tried it differently. I've tested with the new version and all works great. Thanks!
